# Generated by Django 2.2.14 on 2020-08-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_remove_capimage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='capimage',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
