# Generated by Django 2.2.14 on 2020-08-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_capimage_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capimage',
            name='score',
        ),
    ]
